theme: jekyll-theme-cayman

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-156463146-1"
    anonymize_ip         : true